<h2>Giving columns to both the datasets

In [51]:
import pandas as pd
df_euth = pd.read_csv("sick-euthyroid.data", na_values="?", sep=",")

df_euth = df_euth.iloc[:, 1:]

In [48]:
df_sick=pd.read_csv("sick.data",sep=r"[,\|]",engine="python",na_values="?")

In [49]:
df_sick = df_sick.iloc[:, :-1]

In [55]:
import pandas as pd
columns=["age","sex","on_thyroxine","query_on_thyroxine","on_antithyroid_medication","sick","pregnant",
"thyroid_surgery","I131_treatment","query_hypothyroid","query_hyperthyroid",
"lithium","goitre","tumor","hypopituitary","psych","TSH_measured","TSH",
"T3_measured","T3","TT4_measured","TT4","T4U_measured","T4U",
"FTI_measured","FTI","TBG_measured","TBG","referral_source","diagnosis"]
column=["age","sex","on_thyroxine","query_on_thyroxine","on_antithyroid_medication",
"thyroid_surgery","query_hypothyroid","query_hyperthyroid","pregnant",
"sick","tumor","lithium","goitre","TSH_measured","TSH","T3_measured",
"T3","TT4_measured","TT4","T4U_measured","T4U","FTI_measured",
"FTI","TBG_measured","TBG"]
# df_sick=pd.read_csv("sick.data",sep=r"[,\|]",
#     engine="python",na_values="?",sep=",")
# df_euth=pd.read_csv("sick-euthyroid.data",names=column,na_values="?",sep=",")
df_sick.columns=columns
df_euth.columns = column

In [56]:
print(df_sick.shape)
print(len(columns))

(2799, 30)
30

In [57]:
df_sick.head()

,age,sex,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,sick,pregnant,thyroid_surgery,I131_treatment,query_hypothyroid,...,TT4_measured,TT4,T4U_measured,T4U,FTI_measured,FTI,TBG_measured,TBG,referral_source,diagnosis
0,23.0,F,f,f,f,f,f,f,f,f,...,t,102.0,f,NaN,f,NaN,f,NaN,other,negative.
1,46.0,M,f,f,f,f,f,f,f,f,...,t,109.0,t,0.91,t,120.0,f,NaN,other,negative.
2,70.0,F,t,f,f,f,f,f,f,f,...,t,175.0,f,NaN,f,NaN,f,NaN,other,negative.
3,70.0,F,f,f,f,f,f,f,f,f,...,t,61.0,t,0.87,t,70.0,f,NaN,SVI,negative.
4,18.0,F,t,f,f,f,f,f,f,f,...,t,183.0,t,1.30,t,141.0,f,NaN,other,negative.

In [58]:
print(df_euth.shape)
print(len(column))

(3162, 25)
25

In [59]:
df_euth.head()

,age,sex,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,thyroid_surgery,query_hypothyroid,query_hyperthyroid,pregnant,sick,...,T3_measured,T3,TT4_measured,TT4,T4U_measured,T4U,FTI_measured,FTI,TBG_measured,TBG
0,45.0,F,f,f,f,f,f,f,f,f,...,y,1.0,y,82.0,y,0.73,y,112.0,n,NaN
1,64.0,F,f,f,f,f,f,f,f,t,...,y,1.0,y,101.0,y,0.82,y,123.0,n,NaN
2,56.0,M,f,f,f,f,f,f,f,f,...,y,0.8,y,76.0,y,0.77,y,99.0,n,NaN
3,78.0,F,t,f,f,f,t,f,f,f,...,y,0.3,y,87.0,y,0.95,y,91.0,n,NaN
4,80.0,M,f,f,f,f,f,f,f,f,...,y,0.8,y,105.0,y,0.88,y,120.0,n,NaN

<h3>making both datasets of same columns first

In [60]:
selected_cols = [
    "age","sex",
    "on_thyroxine","query_on_thyroxine","on_antithyroid_medication",
    "sick","pregnant","thyroid_surgery",
    "query_hypothyroid","query_hyperthyroid",
    "lithium","goitre","tumor",
    "TSH","T3","TT4","T4U","FTI"
]
# These are the columns that we need in our final dataset

In [61]:
for col in selected_cols:
    if col not in df_euth.columns:
        df_euth[col] = None
# This will add the columns present in the final selected list which are not in this dataset

In [62]:
for col in selected_cols:
    if col not in df_sick.columns:
        df_sick[col] = None

In [63]:
df_sick = df_sick[selected_cols]
df_euth = df_euth[selected_cols]
# This will make the datasets in the same order of the selected columns list

<h3>Merging of the datasets

In [64]:
# df_sick["target"] = "sick"
# df_euth["target"] = "normal"
# Now we add the target column to both the datasets
df_final = pd.concat([df_sick, df_euth], axis=0)
# We are now merging both datasets vertically
df_final.to_csv("final_thyroid_dataset.csv", index=False)
# Saving the content into new file without extra indexing

In [65]:
df_final.shape

(5961, 18)

<h3>Handling missing values

In [66]:
df_final.replace({"t":1, "f":0}, inplace=True) 
# t/f become numeric

,age,sex,on_thyroxine,query_on_thyroxine,on_antithyroid_medication,sick,pregnant,thyroid_surgery,query_hypothyroid,query_hyperthyroid,lithium,goitre,tumor,TSH,T3,TT4,T4U,FTI
0,23.0,F,0,0,0,0,0,0,0,0,0,0,0,4.10,2.0,102.0,NaN,NaN
1,46.0,M,0,0,0,0,0,0,0,0,0,0,0,0.98,NaN,109.0,0.91,120.0
2,70.0,F,1,0,0,0,0,0,0,0,0,0,0,0.16,1.9,175.0,NaN,NaN
3,70.0,F,0,0,0,0,0,0,0,0,0,0,0,0.72,1.2,61.0,0.87,70.0
4,18.0,F,1,0,0,0,0,0,0,0,0,0,0,0.03,NaN,183.0,1.30,141.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3157,40.0,F,0,0,0,1,0,0,0,0,0,0,0,2.10,1.2,76.0,0.90,84.0
3158,69.0,F,0,0,0,0,0,0,0,0,0,0,0,2.60,1.8,126.0,1.02,124.0
3159,58.0,F,0,0,0,0,0,0,0,0,0,0,0,5.80,1.7,86.0,0.91,95.0
3160,29.0,F,0,0,0,0,0,0,0,0,0,0,0,0.80,1.8,99.0,1.01,98.0
3161,56.0,F,1,0,0,0,0,0,0,0,0,0,0,0.00,1.8,139.0,0.97,143.0

In [67]:
num_cols = ["TSH","T3","TT4","T4U","FTI","age"]

for col in num_cols:
    df_final[col] = pd.to_numeric(df_final[col], errors="coerce")
# Convert numeric columns

In [68]:
for col in num_cols:
    df_final[col].fillna(df_final[col].median(), inplace=True)
# Missing numeric values

C:\Users\jigya\AppData\Local\Temp\ipykernel_14616\595749997.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_final[col].fillna(df_final[col].median(), inplace=True)
C:\Users\jigya\AppData\Local\Temp\ipykernel_14616\595749997.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_final[col].fillna(df_final[col].median(), inplace=True)
C:\Users\jigya\AppData\Local\Temp\ipykernel_14616\595749997.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_final[col].fillna(df_final[col].median(), inplace=True)
C:\Users\jigya\AppData\Local\Temp\ipykernel_14616\595749997.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_final[col].fillna(df_final[col].median(), inplace=True)
C:\Users\jigya\AppData\Local\Temp\ipykernel_14616\595749997.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_final[col].fillna(df_final[col].median(), inplace=True)
C:\Users\jigya\AppData\Local\Temp\ipykernel_14616\595749997.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_final[col].fillna(df_final[col].median(), inplace=True)

In [70]:
df_final.isnull().sum()

age                           447
sex                           183
on_thyroxine                    0
query_on_thyroxine              0
on_antithyroid_medication       0
sick                            0
pregnant                        0
thyroid_surgery                 0
query_hypothyroid               0
query_hyperthyroid              0
lithium                         0
goitre                          0
tumor                           0
TSH                           751
T3                           1280
TT4                           433
T4U                           545
FTI                           542
dtype: int64

In [ ]:
# # Age
# df_final["age"].fillna(df_final["age"].median(), inplace=True)

# # Sex
# df_final["sex"].fillna(df_final["sex"].mode()[0], inplace=True)

# # Lab values
# for col in ["TSH","T3","TT4","T4U","FTI"]:
#     df_final[col].fillna(df_final[col].median(), inplace=True)

C:\Users\jigya\AppData\Local\Temp\ipykernel_14616\1450384634.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_final["age"].fillna(df_final["age"].median(), inplace=True)
C:\Users\jigya\AppData\Local\Temp\ipykernel_14616\1450384634.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_final["sex"].fillna(df_final["sex"].mode()[0], inplace=True)
C:\Users\jigya\AppData\Local\Temp\ipykernel_14616\1450384634.py:9: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_final[col].fillna(df_final[col].median(), inplace=True)
C:\Users\jigya\AppData\Local\Temp\ipykernel_14616\1450384634.py:9: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_final[col].fillna(df_final[col].median(), inplace=True)
C:\Users\jigya\AppData\Local\Temp\ipykernel_14616\1450384634.py:9: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_final[col].fillna(df_final[col].median(), inplace=True)
C:\Users\jigya\AppData\Local\Temp\ipykernel_14616\1450384634.py:9: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_final[col].fillna(df_final[col].median(), inplace=True)
C:\Users\jigya\AppData\Local\Temp\ipykernel_14616\1450384634.py:9: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_final[col].fillna(df_final[col].median(), inplace=True)

In [73]:
pd.options.mode.chained_assignment = None
df_final["age"] = df_final["age"].fillna(df_final["age"].median())

df_final["sex"] = df_final["sex"].fillna(df_final["sex"].mode()[0])

for col in ["TSH","T3","TT4","T4U","FTI"]:
    df_final[col] = df_final[col].fillna(df_final[col].median())

In [74]:
df_final.isnull().sum()

age                          0
sex                          0
on_thyroxine                 0
query_on_thyroxine           0
on_antithyroid_medication    0
sick                         0
pregnant                     0
thyroid_surgery              0
query_hypothyroid            0
query_hyperthyroid           0
lithium                      0
goitre                       0
tumor                        0
TSH                          0
T3                           0
TT4                          0
T4U                          0
FTI                          0
dtype: int64

In [76]:
df_final.replace({"t":1, "f":0}, inplace=True)

num_cols = ["TSH","T3","TT4","T4U","FTI","age"]

for col in num_cols:
    df_final[col] = pd.to_numeric(df_final[col], errors="coerce")
    df_final[col] = df_final[col].fillna(df_final[col].median())

In [77]:
def classify_thyroid(row):
    if row["TSH"] > 4 and row["FTI"] < 80:
        return "hypothyroid"
    elif row["TSH"] < 0.4 and row["FTI"] > 120:
        return "hyperthyroid"
    else:
        return "normal"

df_final["target"] = df_final.apply(classify_thyroid, axis=1)

In [78]:
df_final.to_csv("cleaned_thyroid_dataset.csv", index=False)

In [82]:
print(df_final.head())
print(df_final.shape)

    age sex on_thyroxine query_on_thyroxine on_antithyroid_medication sick  \
0  23.0   F            0                  0                         0    0
1  46.0   M            0                  0                         0    0
2  70.0   F            1                  0                         0    0
3  70.0   F            0                  0                         0    0
4  18.0   F            1                  0                         0    0

  pregnant thyroid_surgery query_hypothyroid query_hyperthyroid lithium  \
0        0               0                 0                  0       0
1        0               0                 0                  0       0
2        0               0                 0                  0       0
3        0               0                 0                  0       0
4        0               0                 0                  0       0

  goitre tumor   TSH   T3    TT4   T4U    FTI        target
0      0     0  4.10  2.0  102.0  0.97  107.0        normal
1      0     0  0.98  1.9  109.0  0.91  120.0        normal
2      0     0  0.16  1.9  175.0  0.97  107.0        normal
3      0     0  0.72  1.2   61.0  0.87   70.0        normal
4      0     0  0.03  1.9  183.0  1.30  141.0  hyperthyroid
(5961, 19)

In [83]:
df_final.isnull().sum()

age                          0
sex                          0
on_thyroxine                 0
query_on_thyroxine           0
on_antithyroid_medication    0
sick                         0
pregnant                     0
thyroid_surgery              0
query_hypothyroid            0
query_hyperthyroid           0
lithium                      0
goitre                       0
tumor                        0
TSH                          0
T3                           0
TT4                          0
T4U                          0
FTI                          0
target                       0
dtype: int64

In [85]:
df_final["target"].unique()
df_final["target"].value_counts()

target
normal          4682
hyperthyroid     921
hypothyroid      358
Name: count, dtype: int64